def replace_word():

  str = "The New Year is celebrated around the world with excitement, enthusiasm and joy. It marks the ending of the year and the beginning of another as per the Gregorian calendar. This is an important day for people who wish to enter this new year with new resolutions, hope and light. January 01 is marked as the new year when the early Roman calendar became out of sync with the sun. In 46 BC, Julius Caesar, Roman General and Statesman established the Julian calendar after consulting astronomers and mathematicians. This calendar is much similar to the current Gregorian Calendar marking January 01 as the beginning of a year. People across the globe celebrate New Year on different days depending upon the different communities they belong to. In India, the new year is observed on January 01 as per the English calendar. However, as per the Hindu scripture, the new year is marked between March and April. Even though every community celebrates the New Year according to its on the calendar, the English calendar is majorly used to commemorate globally. Most countries celebrate the new year after 12:00 AM in December and welcome January 01 with an open heart. Lavish meals are made, firecrackers are used, people sing songs to bestow good luck for the coming year. As the new year refers to the first day of the year, it tends to bring happiness and hope to the lives of people. It marks the fresh beginning of life where people can leave behind all their negative energies and start afresh. There is a common tradition of new year resolutions wherein people set different goals for themselves to achieve in that year. It helps them to take small steps towards positive energy and build a good life for themselves and their beloved one’s."
  word_to_replace = input("Enter the word to replace: ")
  word_replacement = input("Enter the word replacement: ")
  print(str.replace(word_to_replace, word_replacement))

replace_word()

